### PR TITLE
feat: add demo user column to users table

### LINKED ISSUE #34: Add `demo_user` column to `users`
Contributes to https://github.com/ck3g/homebugh/issues/33

Add a boolean column `demo_user` to the `users` table with the default value of `false`.

### PR DESCRIPTION
**Pull request by phunq-0851**
Fixes #34 

Changes proposed in this pull request:

- Add demo_user column to users table

### CODE REVIEW

**Comment by phunq-0851** [comment]
@ck3g hei bros, i have done this task, sorry for the late because i've some error when install in my new computer.
Please check this pull request for me :D
p/s: Thank you for supporting hacktoberfest

**Comment by ck3g** [comment]
Hey @phunq-0851 
Thank you. But I think you're slightly fast. 😃  To count for Hacktorberfest, the PR needs to be created in October.

> Pull requests created before Oct 1 but merged or marked as ready for review after do not count.

https://hacktoberfest.digitalocean.com/faq

So feel free to close it, and reopen on Oct 1st.

**Comment by phunq-0851** [comment]
@ck3g  omg, I haven't read carefully, i will close this pull and open it on Oct 1st

**Comment by phunq-0851** [comment]
Is it possible to open this pull request :D @ck3g

**Comment by ck3g** [comment]
I assume you just need to create new one

**Pull request closed without merging**
