### PR TITLE
allow update show in summary in account edit page

### LINKED ISSUE #59: Allow to update `show_in_summary` value on edit account page
Allow to update `show_in_summary` value on edit account page (`/accounts/:id/edit`).

Contributes to https://github.com/ck3g/homebugh/issues/32

Depends on https://github.com/ck3g/homebugh/issues/57

### PR DESCRIPTION
**Pull request by phunq-0851**
Fixes #59 

Changes proposed in this pull request:

- Allow to update `show_in_summary` value on edit account page
Peek 2020-10-09 16-28

### CODE REVIEW

**Comment by phunq-0851** [comment]
@ck3g hey bros, can you check pr for me and give me complete hacktoberfest :D

**Comment by ck3g** [comment]
Even though this iOS-like slider looks nice, I would prefer to stick to the default style for checkboxes. Could you please update the solution to use a default style?

There is an example of a checkbox https://github.com/ck3g/homebugh/blob/5ecb501407dcd2106467af16e20f34c93504beb6/app/views/categories/_form.html.haml#L4-L7

**Comment by phunq-0851** [comment]
@ck3g yeahh, i will update it to default soon

**Comment by ck3g** [comment]
Closing in favor of https://github.com/ck3g/homebugh/pull/82

**Pull request closed without merging**
