### PR TITLE
Show accounts in the summary when show_in_summary is true

### PR DESCRIPTION
**Pull request by m8051**
Fixes https://github.com/ck3g/homebugh/issues/60

Changes proposed in this pull request:

- Based on https://github.com/ck3g/homebugh/issues/57 and https://github.com/ck3g/homebugh/issues/58, this PR attempts to display in the accounts summary only those accounts which show_in_summary is enabled.

### CODE REVIEW

**Comment by m8051** [comment]
@ck3g let me know if this is what you have in mind or if I missed something.

Thanks in advance.

**Comment by ck3g** [comment]
Hey @m8051 

Even though that solution can work, I think the better way would be to add a [scope](https://guides.rubyonrails.org/active_record_querying.html#scopes) similar to [`Category.active`](https://github.com/ck3g/homebugh/blob/685346b34d7e884bdaa4ce9d4183db5c27ae4535/app/models/category.rb#L16) and use it here. In this case, it will iterate only through the "active" and "show_in_summary" accounts.

Do you mind updating the solution to use [a Rails scope](https://guides.rubyonrails.org/active_record_querying.html#scopes)?

**Comment by m8051** [comment]
> Hey @m8051
> 
> Even though that solution can work, I think the better way would be to add a [scope](https://guides.rubyonrails.org/active_record_querying.html#scopes) similar to [`Category.active`](https://github.com/ck3g/homebugh/blob/685346b34d7e884bdaa4ce9d4183db5c27ae4535/app/models/category.rb#L16) and use it here. In this case, it will iterate only through the "active" and "show_in_summary" accounts.
> 
> Do you mind updating the solution to use [a Rails scope](https://guides.rubyonrails.org/active_record_querying.html#scopes)?

Hi @ck3g , I don't mind at all, I will take a look at that scope and update the PR accordingly, thanks for the heads up.

**Comment by ck3g** [comment]
Looks great. Thanks!

**Pull request merged**
